# Generated by Django 6.0.3 on 2026-03-24 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('participo_devocional', models.BooleanField(default=False, verbose_name='Participó del devocional')),
                ('convocado_para', models.CharField(choices=[('consolidar', 'Consolidar'), ('ministrar', 'Ministrar'), ('ambos', 'Ambos')], max_length=20, verbose_name='Convocado para')),
                ('color_equipo', models.CharField(choices=[('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Naranja', 'Naranja'), ('Morado', 'Morado')], max_length=20, verbose_name='Color de equipo')),
                ('culto', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, verbose_name='Culto AM o PM')),
                ('nombre_apellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('lider_celula', models.CharField(max_length=200, verbose_name='Líder de Célula')),
                ('linea', models.CharField(max_length=200, verbose_name='Línea a la que pertenece')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
